-- CREATING TABLE
CREATE TABLE OEETEST (
ID INT NOT NULL IDENTITY(1, 1),
StrDate VARCHAR(255),
OEE INT
);

-- ADD ROW TO THE TABLE
INSERT INTO OEE 
VALUES ('VAL', 121); 

-- DELETE ROW FROM THE TABLE
DELETE FROM OEE WHERE ID = 2; 

-- SHOW ALL TABLE ORDERED BY ID
SELECT * FROM OEE ORDER BY ID
